@startuml
rnote left of James: foo
rnote right of Patric #white
ern
endrnote
rnote right of Patric #white
e_rn
end rnote
rnote right of Patric #white
e_n
end note
rnote right of Patric #white
en
endnote
rnote right of Patric #white
ehn
endhnote
hnote left of Bob: foo
hnote right of Bob #white
ern
endhnote
hnote right of Bob #white
ern
end hnote
hnote right of Bob #white
ern
end note
hnote right of Bob #white
ern
endnote
@enduml