@startuml Sequence
Alice->Bob: Authentication Request
Bob --> Alice
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
Bob -> "James Smith": space in name
@enduml