@startuml Sequence
participant Participant
actor Actor   #red
boundary Boundary
control Control
entity Entity
database Database
collections Collections

Alice->Bob: Authentication Request
Bob --> Alice
Alice -> Bob: Another authentication Request
Alice <-- Bob: another authentication Response
Bob -> "James Smith": space in name
@enduml